// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warning42c91945c202666dd5b9ed0e703cf615445026dd57622e60d881355fb7ed32f4() {}
