// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warningd2c834ca627769a4df0cbe0d678edc9b6e999f5b0c3fd9a45b4a771d279787a5() {}
