// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warning050ee7910544e2b3b343ea5c0515c38911c5435d3ab02092ebc5090b202302f5() {}
