// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warningd0c728cb5ea4a3623dea9deee431f9f64ccee6c2a7edec721cd6161301bd7670() {}
