// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warningb1fa928f5107725dc9efd2a4eb0ab28abd8331a413b25e8ff40a4c8fa06dd78a() {}
