// This file is autogenerated. Changes will be overwritten.
// No files found that require moc or the moc files are included
void cmake_automoc_silence_linker_warning4325cd71d6b1a5572480b44b5c15d775417b52a916c55d80bf09607789a2397b() {}
