// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_SiYi.cpp"
#include "EWIEGA46WW/moc_SiYiCamera.cpp"
#include "EWIEGA46WW/moc_SiYiCrcApi.cpp"
#include "EWIEGA46WW/moc_SiYiTcpClient.cpp"
#include "EWIEGA46WW/moc_SiYiTransmitter.cpp"
