name: LEAF_FC ARM Libs

on:
  release:
    types: [created] # our habit: releases are created from a tag from a non-main branch sourced from dev-sitl

env:
  SOURCE_DIR:   ${{ github.workspace }}/HEAR_Docker


jobs:
  build:
    runs-on: Linux_ARM64_16core
    strategy:
      matrix:
        include:
          - target: ORIN
            target_lower: orin
          - target: RPI
            target_lower: rpi
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      # 🛠️ CLONE HEAR_Docker
      - name: Clone and HEAR_Docker repository
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          echo "🔄 Cloning HEAR_Docker repository ..."
          rm -rf HEAR_Docker

          # Clone repository with shallow clone for better performance
          git clone --depth 1 \
            "https://x-access-token:${GH_TOKEN}@github.com/DroneLeaf/HEAR_Docker.git" HEAR_Docker \
            || { echo "❌ Failed to clone HEAR_Docker repository"; exit 1; }


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container


      - name: Define cache path
        uses: actions/cache@v4
        with:
          path: |
            hashim/docker/cache
          key: ${{ runner.os }}-hashim

      - name: aws credentials #---> [[ to be Deprecated ]]
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR #---> [[ to be Deprecated ]]
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: login to DroneLeaf Docker registry
        id: login-to-docker-registry
        uses: docker/login-action@v3
        with:
          registry: docker.droneleaf.io
          username: ${{ secrets.REG_USERNAME }} #---> should be configured on github repo settings
          password: ${{ secrets.REG_PASSWORD }} #---> should be configured on github repo settings


      - name: chmod
        run: chmod -R +x ./.github


      - name: Get Actor ID #---> [[ there is no need to this step ]]
        id: get_actor_id
        run: |
             echo "::set-output name=actor_id::$(curl -s -H "Authorization: Bearer ${{ secrets.TOKEN }}" https://api.github.com/users/${{ github.actor }} | jq -r .id)"


      - name: Expose GitHub Runtime # loads GitHub’s runtime environment into the job(runtime API, service endpoints, tokens, paths) as env vars for upcoming steps.
        uses: crazy-max/ghaction-github-runtime@v3
      

      - name: Cleanup existing builders
        run: |
          docker buildx ls
          docker buildx rm hashimBuilder || echo "Builder does not exist yet"


      - name: Build and push the tagged docker image
        working-directory: ${{env.SOURCE_DIR}}
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          DOCKER_REGISTRY: docker.droneleaf.io
          IMAGE_TAG: latest
          triggering_actor: ${{ github.triggering_actor }}
          TOKEN: ${{ secrets.TOKEN }}
          target_lower: ${{matrix.target_lower}}
          docker_builder: hashimBuilder
          build_platform: linux/arm64
        run: |
          echo ${{ github.triggering_actor }}
          echo "Building for TARGET: ${{ matrix.target }}"

          export BUILD_TIMESTAMP=$(date +%s)
          FULL_IMAGE_NAME="$ECR_REGISTRY/${ECR_REPOSITORY}_$target_lower:$IMAGE_TAG"
          #FULL_IMAGE_NAME="$DOCKER_REGISTRY/docker/hear_fc_$target_lower:$IMAGE_TAG"
          echo "Full image name: $FULL_IMAGE_NAME" # eg. docker.droneleaf.io/docker/hear_fc_orin:latest


          docker buildx create --name $docker_builder --driver=docker-container

          # 💎 1) for local use 
          # ------------------
          echo "Start Building image for local use"

          docker buildx build . \
          --builder=$docker_builder \
          --platform $build_platform \
          -t hear_fc_${{ matrix.target_lower }}:latest \
          --load \
          --secret id=GITHUB_ID,env=triggering_actor \
          --secret id=GITHUB_TOKEN,env=TOKEN \
          --build-arg TARGET_ORIN="${{ matrix.target == 'ORIN' && 'ON' || 'OFF' }}" \
          --build-arg TARGET="${{ matrix.target }}" \
          --build-arg opencv_url="geohashim/opencv:4.0.0" \
          --build-arg qt_url="geohashim/qt" \
          --build-arg USERNAME="hashim" \
          --build-arg WS_NAME="HEAR_FC" \
          --build-arg IS_PRODUCTION="TRUE" \
          --build-arg COMPILE_BRANCH="dev" \
          --build-arg RANDOM_NUM="$BUILD_TIMESTAMP"

          # 💎 2) for AWS ECR Registry
          # -----------------------
          echo "Start Building for AWS ECR Registry"


          # 💎 3) for DoneLeaf Docker Registry
          # --------------------------------
          echo "Start Building for DroneLeaf Docker Registry"
          


          # 🧹 cleanup docker builder
          # -----------------------
          docker buildx ls
          docker buildx rm $docker_builder || echo "Builder does not exist yet"
        

      - name: Extract folder from Docker container
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          IMAGE_TAG: latest
        run: |
          # Create a container from the image of local use we just built (but don't run it)
          CONTAINER_ID=$(docker create --platform linux/arm64 hear_fc_${{ matrix.target_lower }}:latest)

          # Create directories to hold the extracted files
          rm  -rf extracted_files_${{ matrix.target_lower }}
          mkdir -p extracted_files_${{ matrix.target_lower }} # --> contains /devel/lib/ only and will be compressed and attached to the release files
          mkdir -p upm_extracted_files_${{ matrix.target_lower }}/HEAR_FC # --> used for the upcoming workflow

          # Copy the folder from the container to the host
          docker cp $CONTAINER_ID:/home/hashim/HEAR_FC/devel/lib ./extracted_files_${{ matrix.target_lower }}
          docker cp $CONTAINER_ID:/home/hashim/HEAR_FC ./upm_extracted_files_${{ matrix.target_lower }}/HEAR_FC

          # Remove the container
          docker rm $CONTAINER_ID
          ls -la extracted_files_${{ matrix.target_lower }}

          # Remove the image
          docker rmi hear_fc_${{ matrix.target_lower }}


      - name: Compress extracted files (to attach to the release artifacts later)
        run: |
          tar -czvf leaf_fc_${{ matrix.target_lower }}.tar.gz -C extracted_files_${{ matrix.target_lower }} .

          # List the content to verify
          tar -tvf leaf_fc_${{ matrix.target_lower }}.tar.gz | head -n 10


      - name: Upload folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extracted_files_${{ matrix.target_lower }}
          path: extracted_files_${{ matrix.target_lower }}

          
      - name: Upload upm folder as artifact (used by upm_package_deploy_fc.yml workflow)
        uses: actions/upload-artifact@v4
        with:
          name: upm_extracted_files_${{ matrix.target_lower }}
          path: upm_extracted_files_${{ matrix.target_lower }}    


      - name: Upload firmware to existing release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release_info.outputs.tag }}
          files: |
            leaf_fc_${{ matrix.target_lower }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


