# Triggered by the QGC release dispatcher
name: MacOS Release

on:
  workflow_dispatch: # Manual trigger until resolve compilation issues
  workflow_call:
    inputs:
      release_tag:
        required: false
        type: string
      release_name:
        required: false
        type: string

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}/LeafMC
  QT_VERSION:   5.15.2
  ARTIFACT:     QGroundControl.dmg
  BUILD_TYPE:   ${{ fromJSON('["DailyBuild", "StableBuild"]')[ github.ref_type == 'tag' || contains(github.ref, 'Stable_' ) ] }}

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_call' && (inputs.release_name == '' || contains(inputs.release_name, 'QGC')))
    timeout-minutes: 120
    runs-on:  macos-15
    outputs:
      ARTIFACT_TO_UPLOAD: ${{ steps.set_build_output.outputs.ARTIFACT_TO_UPLOAD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.TOKEN }}

      - name: Get all tags for correct version determination
        working-directory:  ${{ github.workspace }}/LeafMC
        run: |
          git fetch --tags -f --depth 1

      - name: Disable legacy GStreamer framework in post-link
        run: |
          cp ${SOURCE_DIR}/QGCPostLinkInstaller.pri ${SOURCE_DIR}/QGCPostLinkInstaller.pri.bak
          sed -i '' 's|rsync -a --delete /Library/Frameworks/GStreamer.framework|#&|g' ${SOURCE_DIR}/QGCPostLinkInstaller.pri
          sed -i '' 's|ln -sf .*GStreamer.framework/Versions/1.0/libexec/Frameworks|#&|g' ${SOURCE_DIR}/QGCPostLinkInstaller.pri
          sed -i '' 's|install_name_tool -change /Library/Frameworks/GStreamer.framework.*|#&|g' ${SOURCE_DIR}/QGCPostLinkInstaller.pri
          sed -i '' 's|rm -rf \$\${TARGET}.app/Contents/Frameworks/GStreamer.framework/Versions/1.0/.*|#&|g' ${SOURCE_DIR}/QGCPostLinkInstaller.pri



      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version:      ${{ env.QT_VERSION }}
          aqtversion:   ==3.1.*
          host:         mac
          target:       desktop
          dir:          ${{ runner.temp }}
          modules:      qtcharts
          setup-python: true

      - name: Install Gstreamer
        run: |
            #  method1:
            # wget https://gstreamer.freedesktop.org/data/pkg/osx/1.18.6/gstreamer-1.0-devel-1.18.6-x86_64.pkg
            # wget https://gstreamer.freedesktop.org/data/pkg/osx/1.18.6/gstreamer-1.0-1.18.6-x86_64.pkg
            # for package in *.pkg ;
              # do sudo installer -verbose -pkg "$package" -target /
            # done
            # method2:
            # wget -q --show-progress --timeout=60 --tries=3 https://gstreamer.freedesktop.org/data/pkg/osx/1.18.6/gstreamer-1.0-devel-1.18.6-x86_64.pkg
            # wget -q --show-progress --timeout=60 --tries=3 https://gstreamer.freedesktop.org/data/pkg/osx/1.18.6/gstreamer-1.0-1.18.6-x86_64.pkg
            # sudo installer -pkg gstreamer-1.0-devel-1.18.6-x86_64.pkg -target /
            # sudo installer -pkg gstreamer-1.0-1.18.6-x86_64.pkg -target /
            # method3:
            # install GStreamer via Homebrew (arm64-native):
            export HOMEBREW_NO_AUTO_UPDATE=1
            brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly glib pkg-config


      - name: Install ccache
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          brew install ccache

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: echo "timestamp=$(date +%Y-%m-%d-%H-%M-%S)" >> "$GITHUB_OUTPUT"

      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path:         ~/.ccache
          key:          ${{ runner.os }}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          # restore-keys: ${{ runner.os }}-ccache-

      - name: Setup ccache
        run: |
            mkdir -p ~/.ccache
            echo "base_dir = ${GITHUB_WORKSPACE}" > ~/.ccache/ccache.conf
            echo "compression = true" >> ~/.ccache/ccache.conf
            echo "compression_level = 5" >> ~/.ccache/ccache.conf
            ccache -s
            ccache -z

      - name: Create build directory
        run:  mkdir ${{ runner.temp }}/shadow_build_dir

      - name: Build
        working-directory: ${{ runner.temp }}/shadow_build_dir
        run:  |
              export JOBS=$((`sysctl -n hw.ncpu`+1))

              export PKG_CONFIG_PATH="$(brew --prefix)/lib/pkgconfig:$(brew --prefix)/share/pkgconfig"
              export CPATH="$(brew --prefix)/include"
              export LIBRARY_PATH="$(brew --prefix)/lib"

              qmake -r ${SOURCE_DIR}/qgroundcontrol.pro CONFIG+=installer CONFIG+=${BUILD_TYPE}
              make -j$JOBS

        
      - name: ccache post-run
        run:  ccache -s

      - name: get the latest tag for versioning
        run: |
          LATEST_TAG=$(git tag --list 'v*' --sort=-v:refname | head -n 1)
          echo "LATEST_TAG=$LATEST_TAG" >> "$GITHUB_ENV"

      - name: rename dmg with tag
        id: set_build_output
        run: |
          BASENAME="${ARTIFACT%.dmg}"
          FINAL_ARTIFACT="${BASENAME}-${LATEST_TAG}.dmg"
          echo "FINAL_ARTIFACT=$FINAL_ARTIFACT" >> "$GITHUB_ENV"
          echo "ARTIFACT_TO_UPLOAD=$FINAL_ARTIFACT" >> "$GITHUB_OUTPUT"

          mv \
            "${{ runner.temp }}/shadow_build_dir/package/$ARTIFACT" \
            "${{ runner.temp }}/shadow_build_dir/package/$FINAL_ARTIFACT"


      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FINAL_ARTIFACT }}
          path: ${{ runner.temp }}/shadow_build_dir/package/${{ env.FINAL_ARTIFACT }}

      - name: Publish artifact to GitHub release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          gh release upload ${{ inputs.release_tag || github.event.release.tag_name }} ${{ runner.temp }}/shadow_build_dir/package/$FINAL_ARTIFACT
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}


      - name: summary
        run: |
          {
            echo "### 📋 PROCESSING SUMMARY"
            echo ''
            echo "#### Job run ID: ${{ github.run_id }}"
            echo "#### Triggering actor: ${{ github.triggering_actor }}"
            echo "#### Branch/Version: ${{ github.ref_name }}"
            echo "#### Processing completed at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
            echo ''
            echo '##### To download the package:'
            echo 'visit: https://repo.droneleaf.io/download'
            echo ''
            echo "✅ Workflow completed successfully!"
          } >> "$GITHUB_STEP_SUMMARY"
  upload:
    needs: build
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/upload-qgc
        with:
          artifact_type: macos
          artifact: ${{ runner.temp }}/shadow_build_dir/package/${{ needs.build.outputs.ARTIFACT_TO_UPLOAD }}
          server: ${{ secrets.REPO_SERVER_IP }}
          ssh_private_key: ${{ secrets.REPO_SSH_KEY }}